# Python env   : Python v3.12.0
# -*- coding: utf-8 -*-
# @Time    : 2025/4/14 上午10:44
# @Author  : 李清水
# @File    : editor.py
# @Description : WS2812像素矩阵编辑器GUI工具，支持可视化编辑和JSON配置导入导出

# ======================================== 导入相关模块 =========================================

import tkinter as tk
from tkinter import colorchooser, filedialog, messagebox, simpledialog
import json

# ======================================== 全局变量 ============================================

# ======================================== 功能函数 ============================================

def rgb565_to_rgb888(rgb565):
    """高精度RGB565转RGB888（使用硬件级优化算法）"""
    try:
        r = (rgb565 >> 11) & 0x1F
        g = (rgb565 >> 5) & 0x3F
        b = rgb565 & 0x1F
        return (
            (r * 527 + 23) >> 6,
            (g * 259 + 33) >> 6,
            (b * 527 + 23) >> 6
        )
    except Exception as e:
        messagebox.showerror("转换错误", f"RGB565转RGB888时发生错误: {e}")


def rgb888_to_rgb565(r, g, b):
    """符合嵌入式系统标准的RGB888转RGB565（含自动溢出保护）"""
    try:
        r = min(max(r, 0), 255)
        g = min(max(g, 0), 255)
        b = min(max(b, 0), 255)
        return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
    except Exception as e:
        messagebox.showerror("转换错误", f"RGB888转RGB565时发生错误: {e}")


def rgb_to_hex(rgb_tuple):
    """将RGB元组转换为十六进制颜色代码"""
    try:
        return "#{:02x}{:02x}{:02x}".format(*rgb_tuple)
    except Exception as e:
        messagebox.showerror("转换错误", f"RGB转十六进制时发生错误: {e}")
# ======================================== 自定义类 ============================================

class PixelEditor:
    def __init__(self, parent_container, json_file=None):
        # 添加窗口类型判断
        if isinstance(parent_container, tk.Toplevel):
            self.root = tk.Frame(parent_container)
            self.root.pack(expand=True, fill="both")
        else:
            self.root = parent_container

        # 初始化撤销栈、像素大小参数和矩形ID存储
        self.undo_stack = []
        self.default_pixel_size = 30
        self.pixel_size = self.default_pixel_size
        self.current_color = (255, 255, 255)
        self.rect_ids = []  # 存储每个像素的矩形ID

        # 默认模板
        self.data_template = {
            "pixels": [],
            "width": 8,
            "height": 8,
            "description": "Generated by WS2812 Driver System",
            "version": 1.2
        }

        self.create_widgets()

        if json_file:
            self.load_json(json_file)
        else:
            self.initialize_default()

        self.draw_pixels()

    def initialize_default(self):
        """生成默认测试图案"""
        self.data = self.data_template.copy()
        self.data["pixels"] = [
            rgb888_to_rgb565(255, 0, 0) if x < 4 else rgb888_to_rgb565(0, 255, 0)
            for _ in range(8) for x in range(8)
        ]

    def new_template(self):
        """新建纯白模板，支持自定义尺寸并自适应像素大小"""
        try:
            self.root.lift()
            w = simpledialog.askinteger("宽度", "请输入模板宽度:", parent=self.root, minvalue=1, maxvalue=256)
            if w is None: return
            h = simpledialog.askinteger("高度", "请输入模板高度:", parent=self.root, minvalue=1, maxvalue=128)
            if h is None: return

            if w > 256 or h > 128:
                messagebox.showwarning("尺寸超限", "宽度<=256，高度<=128", parent=self.root)
                return

            max_w = (self.root.winfo_screenwidth() * 2) // 3
            max_h = (self.root.winfo_screenheight() * 2) // 3
            cell_w = max_w // w
            cell_h = max_h // h
            self.pixel_size = max(5, min(self.default_pixel_size, cell_w, cell_h))

            white = rgb888_to_rgb565(255, 255, 255)
            self.data = {"pixels": [white] * (w * h), "width": w, "height": h,
                         "description": "Pure white template", "version": 1.0}
            self.undo_stack.clear()
            self.canvas.config(width=w * self.pixel_size, height=h * self.pixel_size)
            self.draw_pixels()
            self.status_label.config(text=f"已创建 {w}×{h} 模板")
        except Exception as e:
            messagebox.showerror("新建错误", f"错误: {e}")

    def create_widgets(self):
        """创建UI组件"""
        try:
            self.canvas = tk.Canvas(self.root, bg="#404040")
            self.canvas.pack(padx=5, pady=5, expand=True, fill=tk.BOTH)
            self.canvas.bind("<Button-1>", self.on_pixel_click)
            self.canvas.bind("<B1-Motion>", self.on_pixel_drag)

            ctrl = tk.Frame(self.root)
            ctrl.pack(pady=5)
            self.color_preview = tk.Label(ctrl, width=6, height=2, bg=rgb_to_hex(self.current_color))
            self.color_preview.pack(side=tk.LEFT, padx=5)
            for txt, cmd in [("新建模板", self.new_template),
                             ("选择颜色", self.choose_color),
                             ("导入JSON", self.load_file),
                             ("保存JSON", self.save_file),
                             ("撤销", self.undo)]:
                tk.Button(ctrl, text=txt, width=8, command=cmd).pack(side=tk.LEFT, padx=5)

            self.status_label = tk.Label(self.root, text="欢迎！", bd=1, relief=tk.SUNKEN, anchor=tk.W)
            self.status_label.pack(side=tk.BOTTOM, fill=tk.X)
        except Exception as e:
            messagebox.showerror("UI错误", str(e))

    def draw_pixels(self):
        """初始化或重绘整个像素矩阵"""
        self.canvas.delete("all")
        self.rect_ids = []
        w, h = self.data["width"], self.data["height"]
        for y in range(h):
            row = []
            for x in range(w):
                idx = y * w + x
                color = rgb565_to_rgb888(self.data["pixels"][idx])
                hexc = rgb_to_hex(color)
                x0, y0 = x * self.pixel_size, y * self.pixel_size
                rid = self.canvas.create_rectangle(x0, y0, x0 + self.pixel_size,
                                                   y0 + self.pixel_size,
                                                   fill=hexc, outline="gray")
                row.append(rid)
            self.rect_ids.append(row)

    def on_pixel_click(self, event):
        """点击更新单个像素"""
        try:
            x, y = event.x // self.pixel_size, event.y // self.pixel_size
            if 0 <= x < self.data["width"] and 0 <= y < self.data["height"]:
                self.undo_stack.append(self.data["pixels"][:])
                idx = y * self.data["width"] + x
                self.data["pixels"][idx] = rgb888_to_rgb565(*self.current_color)
                hexc = rgb_to_hex(rgb565_to_rgb888(self.data["pixels"][idx]))
                self.canvas.itemconfig(self.rect_ids[y][x], fill=hexc)
        except Exception as e:
            messagebox.showerror("点击错误", str(e))

    def on_pixel_drag(self, event):
        """拖拽更新像素"""
        try:
            x, y = event.x // self.pixel_size, event.y // self.pixel_size
            if 0 <= x < self.data["width"] and 0 <= y < self.data["height"]:
                idx = y * self.data["width"] + x
                self.data["pixels"][idx] = rgb888_to_rgb565(*self.current_color)
                hexc = rgb_to_hex(rgb565_to_rgb888(self.data["pixels"][idx]))
                self.canvas.itemconfig(self.rect_ids[y][x], fill=hexc)
        except Exception as e:
            messagebox.showerror("拖拽错误", str(e))

    def choose_color(self):
        """打开颜色选择器"""
        try:
            clr = colorchooser.askcolor(parent=self.root)
            if clr[0]:
                self.current_color = tuple(map(int, clr[0]))
                self.color_preview.config(bg=rgb_to_hex(self.current_color))
        except Exception as e:
            messagebox.showerror("颜色错误", str(e))

    def load_json(self, path):
        """加载并检测JSON，并根据尺寸自适应像素大小"""
        try:
            with open(path) as f:
                d = json.load(f)
            for k in ("pixels", "width", "height"): assert k in d
            self.data = d
            # 根据新尺寸重新计算像素格大小
            w, h = d["width"], d["height"]
            max_w = (self.root.winfo_screenwidth() * 2) // 3
            max_h = (self.root.winfo_screenheight() * 2) // 3
            cell_w = max_w // w
            cell_h = max_h // h
            self.pixel_size = max(5, min(self.default_pixel_size, cell_w, cell_h))
            self.canvas.config(width=w * self.pixel_size,
                               height=h * self.pixel_size)
            self.undo_stack.clear()
            self.draw_pixels()
            self.status_label.config(text="加载成功！")
        except Exception as e:
            messagebox.showerror("加载错误", str(e))

    def load_file(self):
        try:
            # 获取编辑器窗口的顶层窗口
            parent_window = self.root.winfo_toplevel()
            fp = filedialog.askopenfilename(
                parent=parent_window,  # 关键修改：指定父窗口
                defaultextension=".json",
                filetypes=[("JSON", "*.json")]
            )
            if fp:
                self.load_json(fp)
        except Exception as e:
            messagebox.showerror("文件错误", str(e), parent=parent_window)

    def save_file(self):
        try:
            parent_window = self.root.winfo_toplevel()
            fp = filedialog.asksaveasfilename(
                parent=parent_window,  # 关键修改：指定父窗口
                defaultextension=".json",
                filetypes=[("JSON", "*.json")]
            )
            if fp:
                with open(fp, 'w') as f:
                    json.dump(self.data, f, indent=4)
                messagebox.showinfo("保存成功", "已保存", parent=parent_window)
        except Exception as e:
            messagebox.showerror("保存错误", str(e), parent=parent_window)

    def undo(self):
        """撤销操作"""
        if self.undo_stack:
            self.data["pixels"] = self.undo_stack.pop()
            self.draw_pixels()

    def center_window(self, w, h):
        """居中窗口"""
        sw, sh = self.root.winfo_screenwidth(), self.root.winfo_screenheight()
        x, y = (sw - w) // 2, (sh - h) // 2
        self.root.geometry(f"{w}x{h}+{x}+{y}")

# ======================================== 初始化配置 ==========================================

# ========================================  主程序  ===========================================

if __name__ == "__main__":
    # 示例用法
    root = tk.Tk()

    # 方式2：加载已有配置
    editor = PixelEditor(root, "G:/NeopixelMatrixTool/out/color_test.json")

    root.mainloop()